# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  # - name: Home
  #   url: /#top
  #   weight: 1

  - name: About
    url: about
    weight: 100

  #   hasChildren: true
  # - parent: About
  #   name: Resume
  #   url: /about/resume/
  #   weight: 110
  # - parent: About
  #   name: CV
  #   ulr: /about/cv/
  #   weight: 120

  - name: Research
    url: research
    weight: 200
    hasChildren: true

  - parent: Research
    name: Contents
    url: research/contents
    weight: 210

  - parent: Research
    name: Fields
    url: research/fields
    weight: 220


  - name: Projects
    url: project
    weight: 300
    hasChildren: true

  - parent: Projects
    name: Side
    url: project/side
    weight: 310
  - parent: Projects
    name: Course
    url: project/course
    weight: 320
  - parent: Projects
    name: Collaborative
    url: project/collabo
    weight: 330
  
  - name: Activity
    url: activity
    weight: 400
    hasChildren: true
  - parent: Activity
    name: Club
    url: activity/club
    weight: 410
  - parent: Activity
    name: Awards
    url: activity/awards
    weight: 420
  - parent: Activity
    name: Experience
    url: activity/experience
    weight: 430
    
  - name: Personal
    url: post
    weight: 500
  - parent: Personal
    name: Event
    url: event
    weight: 510
  - parent: Personal
    name: ETC
    url: etc
    weight: 520
  - parent: Personal
    name: Blog
    url: blog/
    weght: 530

  - name: Contact
    url: contact
    weight: 600