# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /#top
    weight: 1

  - name: About
    url: about
    weight: 100

  #   hasChildren: true
  # - parent: About
  #   name: Resume
  #   url: /about/resume/
  #   weight: 110
  # - parent: About
  #   name: CV
  #   ulr: /about/cv/
  #   weight: 120

  - name: Research
    url: field
    weight: 200
    hasChildren: true

  - parent: Research
    name: Research Fields
    url: field
    weight: 210

  - name: Projects
    url: project
    weight: 300
    hasChildren: true

  - parent: Projects
    name: Side-project
    url: project
    weight: 310
  - parent: Projects
    name: Course-project
    url: project
    weight: 320
  - parent: Projects
    name: collaborative-project
    url: project
    weight: 330
  - parent: Projects
    name: research-project
    url: project
    weight: 340
  
  - name: Activity
    url: activity
    weight: 400
    hasChildren: true
  - parent: Activity
    name: club
    url: club
    weight: 410
  - parent: Activity
    name: Awards
    url: activity
    weight: 420
  - parent: Activity
    name: abroad
    url: activity
    weight: 430
    
  - name: Personal
    url: post
    weight: 500
  - parent: Personal
    name: event
    url: event
    weight: 510
  - parent: Personal
    name: ETC
    url: etc
    weight: 520
  - parent: Personal
    name: Blog
    url: blog/
    weght: 530

  - name: Contact
    url: contact
    weight: 600