# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/



# Appearance
appearance:
  theme_night: custom
  theme_day: custom
  font: native
  font_size: L

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: 'choi'
    description: 'seoharu.github.io : 최서연의 깃허브페이지'
    twitter: 'GetResearchDev'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''
    bing: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    align: c
    show_logo: true
    fixed_to_top: true
    logo:
      text: ""
      # Logo filename in `assets/media/` folder
      filename: "logo.svg"
    button:
      enable: true
      text: "seoharu"
      url: "https://seoharu.github.io/"
    show_language: true
    show_day_night: true
    show_search: true
    show_theme_chooser: true

    
# Site footer
footer:
  copyright:
    notice: '© {2024} Me. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: 'Sep 1, 2024'
  time_format: '14:30 PM'


# Site features

features:
  syntax_highlighter:
    enable: true
    extra_languages:
      - r
      - latex
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/seoharu/seoharu.github.io'
    branch: main
  avatar:
    gravatar: false
    shape: circle
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
    giscus:
      repo: ''
      repo_id: ''
      category: ''
      category_id: ''
  search:
    provider: wowchemy
  map:
    provider: 'mapnik'
    api_key: ''
    zoom: 15

# Extensions

extensions:
  decap_cms:
    branch: main
    local_backend: false
  academicons:
    enable: true

name: 최서연
role: 학생
organization: 전북대학교 컴퓨터공학부
organization_url: 'https://csai.jbnu.ac.kr/csai/index.do'
email: 'yunseul@jbnu.ac.kr'

ogImage: "assets/media/icon.png"